name: Update Activity Log

on:
  schedule:
    # Corre automáticamente cada día a las 00:00 UTC
    - cron: '0 0 * * *'
  workflow_dispatch:  # Permite ejecutarlo manualmente

jobs:
  update-activity:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Update README with recent activity
        uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          COMMIT_MSG: 'Update activity log'
          MAX_LINES: 10
